# Generated by Django 4.1.13 on 2025-05-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_oder_order_rename_oderitem_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
